# Build Gsmc in a stock Go builder container
FROM golang:1.12-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /go-simongdiuma
RUN cd /go-simongdiuma && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /go-simongdiuma/build/bin/* /usr/local/bin/

EXPOSE 6345 6346 22030 22030/udp
